### ISSUE TITLE
Run this project

### ISSUE THREAD

**Issue by luisfilipemalheiro** [SysCV/sam-hq#13]
Hi everyone,

How run this project with Mac M1 after install opencv-python pycocotools matplotlib onnxruntime onnx?

And if i add new image? How can I predict the result of the new image?

**Comment by lkeab** [comment]
Hi, it should be similar to run sam on Mac m1, you can read [this article](https://tnmthai.medium.com/segment-anything-model-sam-on-apple-silicon-m1-and-m2-5cdb3f781b27) for more information.

For adding new images, you can modify demo_hq_sam.py(https://github.com/SysCV/sam-hq/blob/main/demo/demo_hqsam.py), following our provided image examples in this file.  and then excute `python demo/demo_hqsam.py`.

**Comment by luisfilipemalheiro** [comment]
Thanks for support
