### ISSUE TITLE
Any guidelines for an hq_token_only parameter?

### ISSUE THREAD

**Issue by JW-xiilab** [SysCV/sam-hq#21]
Big applause for such a decent work!

Perhaps, is there any guidelines when using "hq_token_only" parameter in inference stage?

Heuristally, the performance of this paramater seems to be depending on the details of the image(or an object which needed to be masked). Even with the example images given in "demo", some images result in better segementation of the object, while on the other situation, the slightly worse performance on segmenation of details. 

If your team also had an heuristic approach to this parameter, would you suggest any ideas when this parameter works more effectively than having it as "False"?

Thanks in advance, and sorry if I have missed the explanation in the paper.

**Comment by lkeab** [comment]
Hi, thanks for watching our work. We provide guidelines for using this parameter in the comments [here](https://github.com/SysCV/sam-hq/blob/main/demo/demo_hqsam.py#L69) L69 to L75.

**Comment by JW-xiilab** [comment]
Thanks a lot for the reply. 

I must have missed that part even while working on that py.
