### ISSUE TITLE
pypi package?

### ISSUE THREAD

**Issue by WASasquatch** [SysCV/sam-hq#22]
Any plans to create a pypi package for PIP to simply import and use the necessary packages across platofrms, and use from APIs and software?

**Comment by lkeab** [comment]
Hi, thanks for the suggestion. We have the plans to build it and will update when it is finished.

**Comment by MattConflitti** [comment]
Can install it in a similar way to regular SAM repo: 
- `pip install git+https://github.com/SysCV/sam-hq.git` or
- `poetry add git+https://github.com/SysCV/sam-hq.git`

**Comment by lkeab** [comment]
Hi, we provide the pip installation [here](https://github.com/SysCV/sam-hq#quick-installation-via-pip).

**Comment by WASasquatch** [comment]
Awesome, this is great. Thank you!
