### ISSUE TITLE
About HQSEG-44K

### ISSUE THREAD

**Issue by lostkevin** [SysCV/sam-hq#26]
Thanks for the excellent job! I am planning to do some fine-tuning on the SAM model with HQSEG-44K dataset. However, when I prepared the dataset, I found several issues:

1. Some images in FSS are never labeled, like bamboo_slip/7.png
2. Some images in MSRA-10K are mislabeled, like 97915.jpg
3. The DUT-OMRON dataset only contains 5168 images, while actually the DUTS dataset contains 15572 images (including training and val splits). I cannot figure out which dataset is truly used in the HQSEG-44K.

Can you tell us more dataset preparation details? Thanks!

**Comment by lkeab** [comment]
hi, we will release the training instructions and codes in the beginning of July, which also includes the datasets preparation and downloading.

**Comment by lostkevin** [comment]
Thanks!
