### ISSUE TITLE
Error in paper about Params of SAM?

### ISSUE THREAD

**Issue by shipengai** [SysCV/sam-hq#29]
Hi,
In HQ-SAM paper,  it said that param of SAM-B is 358M.
But, I use the code to count is 93.9M
`model_total_params = sum(p.numel() for p in sam.parameters())`
which is error?

**Comment by shipengai** [comment]
In SAM paper, it said that Vit-B is 91M

**Comment by ymq2017** [comment]
Hi, both are correct. We convert the unit of the parameter from **Number** to **Byte**, which is more commonly used. It is calculated as follows
`sum(p.numel() for p in model.parameters() if p.requires_grad) * 4 / (1024 * 1024)`
Here 4 in the formula means that float32 occupies 4 bytes. 
If you download [the original SAM-B checkpoint](https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth), you will find that it is 358MB.
