### ISSUE TITLE
Not adding hq_tokens, directly use the sam tokens

### ISSUE THREAD

**Issue by chiaitian** [SysCV/sam-hq#38]
Hi, have you tested not adding hq_tokens, directly use the sam tokens with the fused image features

**Comment by lkeab** [comment]
please refer to table 4 of the paper on  "Finetune SAM’s output token".

**Comment by chiaitian** [comment]
In table 4, "Finetune SAM’s decoder" and "Finetune SAM’s output token" both use the HQ-Feature or not? 
![image](https://github.com/SysCV/sam-hq/assets/8663766/7fb975c5-e413-4cae-a281-1dcd1b3a60b8)

**Comment by Leebh-kor** [comment]
@chiaitian Your question about Table 4 seems crucial to verify the effectiveness of the HQ-output token. Has the issue been closed, and did you receive a separate response? Or have you gained any insights? I'm also very curious about this matter!
Thank you. 😁
