### ISSUE TITLE
Prompt based Sam HQ 

### ISSUE THREAD

**Issue by FBehrad** [SysCV/sam-hq#39]
Hello, 

How can I use a prompt for segmentation (like the demo version)? 

Thank you

**Comment by lkeab** [comment]
hi, we provided the tutorial [here](https://colab.research.google.com/drive/1QwAbn5hsdqKOD5niuBzuqQX4eLCbNKFL?usp=sharing)

**Comment by FBehrad** [comment]
Yes, I saw the tutorial. Thank you so much. 
However, none of the examples in the tutorial use prompt.

**Comment by lkeab** [comment]
That's not true. The variables like input_box or input_points are input prompts.

**Comment by FBehrad** [comment]
Yes, I think I asked my question badly. I am looking for a text prompt not other types of prompts.
Thank you for your quick responses.

**Comment by lkeab** [comment]
we will release codes supporting language prompts soon. please stay tuned.

**Comment by ankitgoyalumd** [comment]
Hi, for the datasets presented in paper, COIFT, HRSOD, DIS, ThinObject5K where can we get prompts for each image?

**Comment by ymq2017** [comment]
> Hi, for the datasets presented in paper, COIFT, HRSOD, DIS, ThinObject5K where can we get prompts for each image?

We use the GT box for each image. It can be obtained by GT mask.
