### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by MohammadVaziriCh** [SysCV/sam-hq#41]
When I want to train HQ_SAM by instruction,I get the error "HQ-SAM: error: unrecognized arguments: --local-rank=0
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 1468) of binary: /usr/bin/python3" in colab.how to resolve it?

**Comment by ymq2017** [comment]
Hi, this [issue](https://github.com/huggingface/pytorch-image-models/issues/1728) might help you. It looks like a PyTorch version problem. You could use torchrun or install a lower version of torch.

**Comment by MohammadVaziriCh** [comment]
I solved it by using torchrun instead of distributed

**Comment by MohammadVaziriCh** [comment]
I solved it by using torchrun instead of distributed
