### ISSUE TITLE
Predictions of baseline MobileSAM inconsistent with official MobileSAM

### ISSUE THREAD

**Issue by daniegr** [SysCV/sam-hq#44]
When running the exact same input image and box prompt with the baseline MobileSAM (available in this repository) and the official MobileSAM model there are differences in predicted masks. I have tried to locate if there are particular differences in the code causing this inconsistent behavior but without luck thus far. I believe this is an urgent issue that should be investigated.

Baseline MobileSAM (SAM-HQ repository) vs Official MobileSAM ([MobileSam repository](https://github.com/ChaoningZhang/MobileSAM)):
![BaselineMobileSAMInconsistency_HQSAMvsMobileSAM_comp](https://github.com/SysCV/sam-hq/assets/8349630/0c20a048-ef56-4124-ba03-060dcb11900e)

**Comment by ymq2017** [comment]
Hi, thank you for this issue. We have compared the inference code of the original SAM and Mobile-SAM. We find the reason.
Original SAM
```
sam = sam_model_registry[model_type](checkpoint=sam_checkpoint)
sam.to(device=device)
predictor = SamPredictor(sam)
```
Mobile SAM
```
sam = sam_model_registry[model_type](checkpoint=sam_checkpoint)
sam.to(device=device)
sam.eval()
predictor = SamPredictor(sam)
```
Mobile-SAM needs to add eval() after the definition. I think it's because TinyViT has some BN layers, Thank you for pointing out the problem, we have modified it in the demo code.

**Comment by daniegr** [comment]
From inference on a few sample images with the revised code, I can now confirm that the baseline model of MobileSAM behaves consistently with the official version of MobileSAM. Thank you very much for your handling this issue quickly!
