### ISSUE TITLE
Whether the ONNX decoder supports only one box input at a time？

### ISSUE THREAD

**Issue by morestart** [SysCV/sam-hq#45]

**Comment by ArasAVMR** [comment]
It's also my question.and is there another way(exept ONNX) to use trained decoder checkpoint (.pth) file?

**Comment by ymq2017** [comment]
Hi, to use multi-box prompt input, we need to re-export the ONNX model and change the dimension of the dummy input. We now provide an example at the end of this [Colab Notebook](https://colab.research.google.com/drive/11U2La49c2IxahzJkAV-EzPqEH3cz_5hq?usp=sharing)

**Comment by morestart** [comment]
Can only specify a fixed quantity? Can dynamic input be supported？
