### ISSUE TITLE
[Feature] Export to ONNX SAM image encoder

### ISSUE THREAD

**Issue by WaterKnight1998** [SysCV/sam-hq#51]
Thank you very much for this incredible model.

I was looking at your guide for exporting the model to ONNX. I didn't understand why you don't want to export the SAM image encoder to ONNX. I think is because you are executing the onnx graph with onnxruntime in CPU.

However, it would be nice to have it for Triton Inference Server with CUDA backend.

**Comment by ymq2017** [comment]
Hi, thanks for watching our work. 
We follow the original SAM's method that only exported the decoder. I think it's the CPU reason as you said. If you want to export the encoder to ONNX, this [pull request](https://github.com/facebookresearch/segment-anything/pull/29) may help.
