### ISSUE TITLE
I wanted to train the model with my images

### ISSUE THREAD

**Issue by sumaoge** [SysCV/sam-hq#57]
I wanted to train the model with my images. 
What should I do?
Is it necessary to make my images to DIS5K dataset?
What software can be used to create DIS5K file/dataset?

**Comment by lkeab** [comment]
Hi, you need to convert your images and masks annotation into the similar format provided in HQ-Seg-44K. You can download HQ-Seg-44K [here](https://huggingface.co/sam-hq-team/sam-hq-training/tree/main/data). For dis, they use [GIMP](https://www.gimp.org/) as their annotation tool but they are also other tools available as long as it can label masks.

**Comment by sumaoge** [comment]
> Hi, you need to convert your images and masks annotation into the similar format provided in HQ-Seg-44K. You can download HQ-Seg-44K [here](https://huggingface.co/sam-hq-team/sam-hq-training/tree/main/data). For dis, they use [GIMP](https://www.gimp.org/) as their annotation tool but they are also other tools available as long as it can label masks.

THANKS!! I ' ll try
