### ISSUE TITLE
how to generate a sliding comparison gif file in the Visual comparison part

### ISSUE THREAD

**Issue by yliuosu** [SysCV/sam-hq#72]
Hi, would you please share some information about how to make a sliding comparison gif file in the Visual comparison part. Thanks

**Comment by lkeab** [comment]
hi, you can refer to the js code implementation [here](https://github.com/pnewton84/pnewton84.github.io/tree/master) and the web demo [here](https://pnewton84.github.io/chindits-in-colour.html) for sliding figures.

**Comment by yliuosu** [comment]
> hi, you can refer to the js code implementation [here](https://github.com/pnewton84/pnewton84.github.io/tree/master) and the web demo [here](https://pnewton84.github.io/chindits-in-colour.html) for sliding figures.

Thanks a lot.
