### ISSUE TITLE
Question about learnable parameters.

### ISSUE THREAD

**Issue by Nastu-Ho** [SysCV/sam-hq#79]
![image](https://github.com/SysCV/sam-hq/assets/39642013/c6a11408-0853-45c5-8d04-0d42cac887f6)
![image](https://github.com/SysCV/sam-hq/assets/39642013/d09a5d15-df88-4cf1-8c3f-5399c344e9fb)
The learnable parameters calculated according to the program are about 1.3M. But the paper says 5.1M, and I'm not quite sure what that's going on.

**Comment by lkeab** [comment]
Hi, please refer to the discussion [here](https://github.com/SysCV/sam-hq/issues/29). The unit is different.

**Comment by Nastu-Ho** [comment]
Could you teach me how to divide SAM's raw weights into image_encoder, prompt_encoder, mask_decoder to store them?
