### ISSUE TITLE
Are the text prompts in the demo used directly as input to sam-hq?

### ISSUE THREAD

**Issue by hyosong86** [SysCV/sam-hq#81]
https://huggingface.co/spaces/sam-hq-team/sam-hq
Are the text prompts in the demo used directly as input to sam-hq?

If so, the computation time would be faster than the "grounded-sam + sam-hq" configuration, which requires several intermediate steps to use the text prompt.

Could you tell me when the code that uses text prompts as input will be released?
Thank you for your great work.

**Comment by lkeab** [comment]
hi, grounded hq-sam and grounded light hq-sam has been supported in [here](https://github.com/IDEA-Research/Grounded-Segment-Anything/tree/main#running_man-grounded-sam-detect-and-segment-everything-with-text-prompt) and [here](https://github.com/IDEA-Research/Grounded-Segment-Anything/tree/main/EfficientSAM).
